# Generated by Django 4.1 on 2023-05-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paymentmethod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], max_length=10)),
                ('token', models.CharField(max_length=255)),
                ('last_paid', models.DateTimeField(blank=True, null=True)),
                ('last_failed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('failed', 'Failed')], default='due', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('next_due', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paymentmethod.card')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
