# Generated by Django 4.1 on 2023-05-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
    ]
