# Generated by Django 4.1 on 2023-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_payment_description_payment_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='terminated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
